// The gear catalog. Each item's primary bonus lands on its own category,
// scaled by rarity (common +10, rare +18, epic +26, legendary +34), with the
// occasional small secondary bonus. Skills gear carries a real backend toolId.
import type { EquipmentItem } from './types';

export const CATALOG: EquipmentItem[] = [
  // ─── Skills (map to real tools) ───────────────────────────────────────────
  {
    id: 'web-search-blade',
    name: 'Web Search Blade',
    category: 'skills',
    icon: '🗡️',
    rarity: 'rare',
    bonuses: { skills: 18, knowledge: 4 },
    toolId: 'web_search',
    desc: 'A keen edge that slices through the open web for fresh intel.',
  },
  {
    id: 'x-search-longbow',
    name: 'X-Search Longbow',
    category: 'skills',
    icon: '🏹',
    rarity: 'rare',
    bonuses: { skills: 18, memory: 3 },
    toolId: 'x_search',
    desc: 'Looses arrows into the timeline to pluck real-time chatter.',
  },
  {
    id: 'code-forge-hammer',
    name: 'Code Forge Hammer',
    category: 'skills',
    icon: '🔨',
    rarity: 'epic',
    bonuses: { skills: 26, reasoning: 4 },
    toolId: 'code_execution',
    desc: 'Hammers raw logic into runnable code at the anvil of execution.',
  },
  {
    id: 'omni-tool',
    name: 'Omni-Tool',
    category: 'skills',
    icon: '🛠️',
    rarity: 'legendary',
    bonuses: { skills: 34, mcp: 6, reasoning: 6 },
    desc: 'A mythic multitool. Radiant power, but wired to no single tool.',
  },

  // ─── MCP (cosmetic / stat only) ───────────────────────────────────────────
  {
    id: 'github-relic',
    name: 'GitHub Relic',
    category: 'mcp',
    icon: '🐙',
    rarity: 'epic',
    bonuses: { mcp: 26, skills: 4 },
    desc: 'An octo-sigil that binds the agent to a realm of repositories.',
  },
  {
    id: 'filesystem-talisman',
    name: 'Filesystem Talisman',
    category: 'mcp',
    icon: '📁',
    rarity: 'rare',
    bonuses: { mcp: 18, memory: 3 },
    desc: 'Opens doorways to every folder in the mortal disk.',
  },
  {
    id: 'slack-sigil',
    name: 'Slack Sigil',
    category: 'mcp',
    icon: '💬',
    rarity: 'common',
    bonuses: { mcp: 10 },
    desc: 'A humble rune that whispers into distant channels.',
  },

  // ─── Knowledge ────────────────────────────────────────────────────────────
  {
    id: 'docs-codex',
    name: 'Docs Codex',
    category: 'knowledge',
    icon: '📘',
    rarity: 'common',
    bonuses: { knowledge: 10 },
    desc: 'A well-thumbed tome of manuals and how-tos.',
  },
  {
    id: 'vector-tome',
    name: 'Vector Tome',
    category: 'knowledge',
    icon: '🧭',
    rarity: 'epic',
    bonuses: { knowledge: 26, memory: 5 },
    desc: 'Embeds a thousand truths into navigable latent space.',
  },
  {
    id: 'wiki-grimoire',
    name: 'Wiki Grimoire',
    category: 'knowledge',
    icon: '📗',
    rarity: 'rare',
    bonuses: { knowledge: 18, reasoning: 3 },
    desc: 'An ever-editing grimoire of the world’s collective lore.',
  },

  // ─── Prompt ───────────────────────────────────────────────────────────────
  {
    id: 'novice-scroll',
    name: 'Novice Scroll',
    category: 'prompt',
    icon: '📜',
    rarity: 'common',
    bonuses: { prompt: 10 },
    desc: 'A starter incantation — simple, but it gets the job done.',
  },
  {
    id: 'expert-sigil',
    name: 'Expert Sigil',
    category: 'prompt',
    icon: '✍️',
    rarity: 'rare',
    bonuses: { prompt: 18, reasoning: 3 },
    desc: 'Finely-tuned phrasing that bends the model to your will.',
  },
  {
    id: 'chain-of-thought-rune',
    name: 'Chain-of-Thought Rune',
    category: 'prompt',
    icon: '🔗',
    rarity: 'epic',
    bonuses: { prompt: 26, reasoning: 6 },
    desc: 'Etches a step-by-step path so the mind never loses its way.',
  },

  // ─── Memory ───────────────────────────────────────────────────────────────
  {
    id: 'short-term-charm',
    name: 'Short-term Charm',
    category: 'memory',
    icon: '🧿',
    rarity: 'common',
    bonuses: { memory: 10 },
    desc: 'Holds the last few turns close, then gently lets them go.',
  },
  {
    id: 'long-context-amulet',
    name: 'Long-Context Amulet',
    category: 'memory',
    icon: '📿',
    rarity: 'epic',
    bonuses: { memory: 26, knowledge: 5 },
    desc: 'A vast amulet that remembers whole sagas without strain.',
  },
  {
    id: 'episodic-locket',
    name: 'Episodic Locket',
    category: 'memory',
    icon: '💾',
    rarity: 'rare',
    bonuses: { memory: 18, prompt: 3 },
    desc: 'Keepsake of past quests, recalled exactly when needed.',
  },

  // ─── Reasoning ────────────────────────────────────────────────────────────
  {
    id: 'grok-crown',
    name: 'Grok-4.3 Crown',
    category: 'reasoning',
    icon: '👑',
    rarity: 'legendary',
    bonuses: { reasoning: 34, prompt: 6, knowledge: 4 },
    desc: 'The sovereign crown of deep thought — nothing outwits it.',
  },
  {
    id: 'multi-agent-diadem',
    name: 'Multi-Agent Diadem',
    category: 'reasoning',
    icon: '💠',
    rarity: 'epic',
    bonuses: { reasoning: 26, mcp: 5 },
    desc: 'Splits the mind into a council of cooperating selves.',
  },
  {
    id: 'logic-circlet',
    name: 'Logic Circlet',
    category: 'reasoning',
    icon: '🔮',
    rarity: 'common',
    bonuses: { reasoning: 10 },
    desc: 'A modest band that keeps deductions crisp and clean.',
  },
];
